sonar.organization=ayush-pardeshi
sonar.projectKey=Ayush-pardeshi_ecommerce-devops-platform

sonar.sources=application/backend,application/frontend

sonar.exclusions=\
**/__pycache__/**,\
**/node_modules/**,\
**/dist/**,\
**/.venv/**,\
**/venv/**,\
**/coverage/**,\
**/zap-reports/**,\
**/*.bak
